# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  'Default'

steps:
- script: echo Running Book Reviews Pipeline!
  displayName: 'Book reviews Pipeline - OneTest Tests'
  
- task: OTSTask@0
  inputs:
    OTSService: 'OneTestServer'
    project: 'BookInfo Istio Project'
    branch: 'Master'
    repo: 'https://github.com/virtualmonster/BookInfo_Istio.git'
    filePath: 'BookInfo/Logical/BookInfo.scm/ReviewsService.opr/BookInfo API Tests.gts'
    ritEnv: 'LP2-EU-51627856'
